In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, save_model, load_model
import pandas as pd
import numpy as np

In [2]:
window_size = 20

# import csv, sort by date so percent change works, drop unneeded columns,
# rename columns, calculate moving averages, calulate percent changes, drop na's
df = pd.read_csv(f"../data/interim/SPY_{window_size}_flattened.csv")

# features to use
items = ["close", "ema", "high", "low", "open", "rsi", "sma", "volume"]
day_counts = [f"_{i}" for i in range(0, window_size -1)]
FEATURE_COLUMNS = []
for day_count in day_counts:
    for item in items:
        FEATURE_COLUMNS.append(f"{item}{day_count}")

df_pred = df[FEATURE_COLUMNS].iloc[-5:]

# File path
filepath = './results/2021-12-02_MIXED-20-huber_loss-adam-LSTM-elu-layers-3-units-1000-b.h5'

# Load the model
model = load_model(filepath, compile = True)

# A few random samples
samples_to_predict = np.array(df_pred)

# Convert into Numpy array
samples_to_predict = samples_to_predict.reshape((samples_to_predict.shape[0], 1, samples_to_predict.shape[1]))

# Generate predictions for samples
predictions = model.predict(samples_to_predict)
print(predictions)

[[ 0.1458  0.579   0.792   0.813 ]
 [ 0.5435 -0.978  -0.4048 -0.9985]
 [-0.967  -0.858  -0.9604 -0.4814]
 [-0.588  -0.951  -0.8555 -0.966 ]
 [ 1.801  -0.9956  0.3167 -0.9995]]


In [3]:
TARGET_COLUMNS = []
for item in ["close", "high", "low", "open"]:
    TARGET_COLUMNS.append(f"{item}_{window_size - 1}")
df[TARGET_COLUMNS].iloc[-5:]

close_19   high_19    low_19   open_19
5417 -6.019399 -3.267932 -4.127482 -1.893078
5418  1.951144  1.020033  1.507010  0.581304
5419 -2.960694 -1.206372 -2.496941 -1.038766
5420 -1.322657  0.190118 -1.639220 -0.200215
5421  1.991047 -2.348125  0.160060 -4.880884