In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, save_model, load_model
import pandas as pd
import numpy as np
from os import listdir
from os.path import isfile, join

In [3]:
onlyfiles = [f for f in listdir('./results') if isfile(join('./results', f))]
onlyfiles = list(filter(lambda thisfilename: '-20-' in thisfilename, onlyfiles))

In [5]:
window_size = 20

# import csv, sort by date so percent change works, drop unneeded columns,
# rename columns, calculate moving averages, calulate percent changes, drop na's
df = pd.read_csv(f"../data/interim/SPY_{window_size}_flattened.csv")

# features to use
items = ["close", "ema", "high", "low", "open", "rsi", "sma", "volume"]
day_counts = [f"_{i}" for i in range(0, window_size -1)]
FEATURE_COLUMNS = []
for day_count in day_counts:
    for item in items:
        FEATURE_COLUMNS.append(f"{item}{day_count}")

df_pred = df[FEATURE_COLUMNS].iloc[-5:]

# Get samples to predict
samples_to_predict = np.array(df_pred)

# Convert into Numpy array
samples_to_predict = samples_to_predict.reshape((samples_to_predict.shape[0], 1, samples_to_predict.shape[1]))

# File path
for model_filepath in onlyfiles:
    model = load_model(f"./results/{model_filepath}", compile=True)
    # Predict
    predictions = model.predict(samples_to_predict)
    print(f"{model_filepath}")
    print(predictions)



2021-12-03_MIXED-20-huber_loss-adam-LSTM-elu-layers-3-units-1000-b.h5
[[-0.376    0.2776   0.1897   0.4932 ]
 [ 2.13     0.8906   1.475    0.01587]
 [-1.      -0.9995  -1.      -0.998  ]
 [-0.8936   0.3726  -0.784    0.2583 ]
 [ 2.191   -0.999    0.354   -1.     ]]
2021-12-03_MIXED-20-huber_loss-adam-LSTM-linear-layers-3-units-1000-b.h5
[[-6.81    -4.582   -4.69    -2.312  ]
 [ 2.264    0.9243   1.833    0.576  ]
 [-3.451   -1.675   -3.133   -1.791  ]
 [-1.695    0.4185  -1.69    -0.00981]
 [ 1.399   -2.648   -0.0815  -4.945  ]]
2021-12-03_MIXED-20-huber_loss-adam-LSTM-selu-layers-3-units-1000-b.h5
[[-1.758   -1.738   -1.757   -1.638  ]
 [ 2.174    0.8423   1.254    0.2445 ]
 [-1.758   -1.301   -1.758   -0.881  ]
 [-1.664    0.368   -1.684    0.02841]
 [ 2.066   -1.757    0.2107  -1.758  ]]
2021-12-03_MIXED-20-huber_loss-adam-LSTM-tanh-layers-3-units-1000-b.h5
[[-1.      -1.      -1.      -0.985  ]
 [ 1.       0.9683   0.972    0.6724 ]
 [-0.9937  -0.8857  -0.998   -0.8438 ]
 [-0.9985 

In [6]:
TARGET_COLUMNS = []
for item in ["close", "high", "low", "open"]:
    TARGET_COLUMNS.append(f"{item}_{window_size - 1}")
df[TARGET_COLUMNS].iloc[-5:]

close_19   high_19    low_19   open_19
5417 -6.019399 -3.267932 -4.127482 -1.893078
5418  1.951144  1.020033  1.507010  0.581304
5419 -2.960694 -1.206372 -2.496941 -1.038766
5420 -1.322657  0.190118 -1.639220 -0.200215
5421  1.991047 -2.348125  0.160060 -4.880884

In [7]:
onlyfiles = [f for f in listdir('./results') if isfile(join('./results', f))]
onlyfiles = list(filter(lambda thisfilename: '-320-' in thisfilename, onlyfiles))

In [8]:
window_size = 320

# import csv, sort by date so percent change works, drop unneeded columns,
# rename columns, calculate moving averages, calulate percent changes, drop na's
df = pd.read_csv(f"../data/interim/SPY_{window_size}_flattened.csv")

# features to use
items = ["close", "ema", "high", "low", "open", "rsi", "sma", "volume"]
day_counts = [f"_{i}" for i in range(0, window_size -1)]
FEATURE_COLUMNS = []
for day_count in day_counts:
    for item in items:
        FEATURE_COLUMNS.append(f"{item}{day_count}")

df_pred = df[FEATURE_COLUMNS].iloc[-5:]

# Get samples to predict
samples_to_predict = np.array(df_pred)

# Convert into Numpy array
samples_to_predict = samples_to_predict.reshape((samples_to_predict.shape[0], 1, samples_to_predict.shape[1]))

# File path
for model_filepath in onlyfiles:
    model = load_model(f"./results/{model_filepath}", compile=True)
    # Predict
    predictions = model.predict(samples_to_predict)
    print(f"{model_filepath}")
    print(predictions)


2021-12-03_MIXED-320-huber_loss-adam-LSTM-elu-layers-3-units-1000-b.h5
[[-1.     -0.995  -1.     -0.927 ]
 [ 0.787   0.588   0.608   0.1448]
 [-1.     -0.995  -1.     -0.7905]
 [-0.9863 -0.996  -0.997  -0.9985]
 [ 1.243  -1.     -0.9346 -1.    ]]
2021-12-03_MIXED-320-huber_loss-adam-LSTM-linear-layers-3-units-1000-b.h5
[[-2.084   -1.342   -2.033   -1.017  ]
 [ 0.9834   0.8247   0.6636   0.3289 ]
 [-2.031   -0.873   -1.805   -0.5083 ]
 [-1.093   -0.04196 -0.8687   0.05487]
 [ 1.954   -1.897   -0.2278  -3.133  ]]
2021-12-03_MIXED-320-huber_loss-adam-LSTM-selu-layers-3-units-1000-b.h5
[[-1.724  -1.391  -1.732  -0.714 ]
 [ 1.046   0.4678  0.781   0.0712]
 [-1.719  -0.7915 -1.591  -0.2223]
 [-0.717  -0.547  -0.5674 -0.2893]
 [ 1.914  -1.539   0.2052 -1.753 ]]
2021-12-03_MIXED-320-huber_loss-adam-LSTM-tanh-layers-3-units-1000-b.h5
[[-1.      -1.      -1.      -1.     ]
 [ 0.9805   0.6763   0.614    0.04697]
 [-1.      -0.9053  -0.999   -0.529  ]
 [-0.9937  -0.256   -0.9287  -0.03009]
 [ 0.98

In [9]:
TARGET_COLUMNS = []
for item in ["close", "high", "low", "open"]:
    TARGET_COLUMNS.append(f"{item}_{window_size - 1}")
df[TARGET_COLUMNS].iloc[-5:]

close_319  high_319   low_319  open_319
4817  -2.626775 -1.746244 -1.840354 -0.984904
4818   1.253305  0.626038  0.822197  0.294759
4819  -2.271752 -0.853583 -1.609466 -0.601101
4820  -1.326710  0.053825 -1.283601 -0.192931
4821   1.586692 -1.726551 -0.091769 -2.696674